'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { students as seed } from '@/services/mock-data'
import { createId, getStudents, saveStudents } from '@/services/mock-auth'

export function StudentList() { const [items,setItems] = useState(seed); const [query,setQuery] = useState(''); useEffect(() => { const saved=getStudents(); if(saved) setItems(saved) },[]); function remove(id:string){ const next=items.filter(s=>s.id!==id); setItems(next); saveStudents(next) } const filtered=items.filter(s=>s.fullName.toLowerCase().includes(query.toLowerCase())); return <div className="app-shell"><main className="main-area"><header className="topbar"><div><span className="eyebrow">School workspace</span><h1>Students</h1></div><Link className="button button-dark" href="/school/students/new">Add student</Link></header><main className="content"><section className="panel"><div className="table-head"><strong>{filtered.length} learners</strong><input aria-label="Search students" className="search-box" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students" /></div>{filtered.map(s=><div className="student-card" key={s.id}><div className="avatar soft">{s.initials}</div><div className="student-main"><strong>{s.fullName}</strong><span>{s.className} · Roll no. {s.rollNo}</span></div><div className="student-metric"><span>Progress</span><b>{s.progress}%</b></div><div className="student-actions"><Link href={`/school/students/${s.id}`}>View</Link><Link href={`/school/students/${s.id}/edit`}>Edit</Link><button onClick={()=>{if(confirm(`Remove ${s.fullName}?`)) remove(s.id)}}>Delete</button></div></div>)}</section></main></main></div> }

export function StudentForm({ id }: { id?: string }) { const [items,setItems]=useState(seed); const existing=items.find(s=>s.id===id); const [name,setName]=useState(existing?.fullName||''); const [className,setClassName]=useState(existing?.className||'Class 4A'); const [rollNo,setRollNo]=useState(existing?.rollNo||''); const [code,setCode]=useState(existing?.studentCode||''); function submit(e:React.FormEvent){e.preventDefault(); const initials=name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(); const next=existing?items.map(s=>s.id===id?{...s,fullName:name,className,rollNo,studentCode:code,initials}:s):[...items,{...seed[0],id:createId(),fullName:name,className,rollNo,studentCode:code,initials}]; saveStudents(next); window.location.href='/school/students'} return <div className="app-shell"><main className="main-area"><header className="topbar"><div><span className="eyebrow">School workspace</span><h1>{existing?'Edit student':'Add student'}</h1></div></header><main className="content"><form className="panel form-panel" onSubmit={submit}><label>Full Name<input required value={name} onChange={e=>setName(e.target.value)} /></label><label>Class<input required value={className} onChange={e=>setClassName(e.target.value)} /></label><label>Roll Number<input required value={rollNo} onChange={e=>setRollNo(e.target.value)} /></label><label>Student Code<input required value={code} onChange={e=>setCode(e.target.value)} /></label><div className="button-row"><button className="button button-dark">{existing?'Save changes':'Create student'}</button><Link className="button button-light" href="/school/students">Cancel</Link></div></form></main></main></div> }
