'use client'
import Link from 'next/link'
import { activities, currentStudent, levels, school, students, teacher } from '@/services/mock-data'
import { StudentWorldDashboard } from '@/components/student/world-scenes'

function Nav({ portal }: { portal: 'school' | 'student' }) { const links = portal === 'school' ? [['/school/dashboard','Dashboard'],['/school/students','Students'],['/school/progress','Progress'],['/school/levels','Levels'],['/school/reports','Reports'],['/school/settings','Settings']] : [['/student/dashboard','Home'],['/student/classes','Learn'],['/student/progress','Progress'],['/student/rewards','Rewards'],['/student/profile','Profile']]; return <aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">T</span>talkora</Link><span className="portal-pill">{portal} portal</span><nav>{links.map(([href,label]) => <Link href={href} key={href}><span className="nav-dot" />{label}</Link>)}</nav><div className="sidebar-bottom"><div className="mini-bubble">{portal === 'school' ? 'Your classroom is growing!' : 'Small steps, big words.'}</div><div className="miss-wrap"><img src="/miss-julie-portrait.png" alt="Miss Julie" /></div></div></aside> }
function Stat({ label, value, accent }: { label:string; value:string; accent:string }) { return <div className={`stat ${accent}`}><span>{label}</span><strong>{value}</strong></div> }
export function SchoolDashboard() { return <div className="app-shell"><Nav portal="school"/><div className="main-area"><header className="topbar"><div><span className="eyebrow">{school.name}</span><h1>Teacher workspace</h1></div><span className="streak">{teacher.name}</span></header><main className="content"><section className="hero-card teacher-hero"><div><span className="eyebrow">Your classroom</span><h2>Let&apos;s make English click today.</h2><p>Welcome back, {teacher.name}. Your students are making wonderful progress.</p><div className="button-row"><Link className="button button-dark" href="/school/students">View students</Link><Link className="button button-light" href="/school/reports">View reports</Link></div></div><div className="miss-wrap"><img src="/miss-julie-portrait.png" alt="Miss Julie welcoming the teacher" /></div></section><div className="stats-grid"><Stat label="Total students" value="124" accent="yellow"/><Stat label="Active this week" value="108" accent="blue"/><Stat label="Average progress" value="74%" accent="green"/><Stat label="Levels completed" value="846" accent="pink"/></div><section className="panel"><div className="section-head"><h3>Students needing attention</h3><Link href="/school/students">See all</Link></div>{students.slice(1,4).map(s => <Link href={`/school/students/${s.id}`} className="student-row" key={s.id}><div className="avatar soft">{s.initials}</div><div className="row-copy"><strong>{s.fullName}</strong><span>{s.className} · {s.learningTime}</span></div><div className="row-progress"><b>{s.progress}%</b><div className="progress-track"><span style={{width:`${s.progress}%`}}/></div></div></Link>)}</section></main></div></div> }
export function StudentDashboard() { return <StudentWorldDashboard /> }
